<script setup lang="ts"></script>
<template>
  <el-table class="w-full" v-loading="false" :data="[]" border height="100%">
    <el-table-column
      align="center"
      fixed
      prop="companyName"
      label="公司"
      width="140"
      sortable
    ></el-table-column>
    <el-table-column
      align="center"
      prop="position"
      label="職務"
      sortable
      width="140"
    ></el-table-column>
    <el-table-column
      align="center"
      prop="jobLevel"
      label="職級"
      width="120"
    ></el-table-column>
    <el-table-column
      align="center"
      prop="relevantExperience"
      label="年資(年)"
      width="120"
      sortable
    ></el-table-column>
    <el-table-column
      align="center"
      prop="currentTenure"
      label="現職(年)"
      width="120"
      sortable
    ></el-table-column>
    <el-table-column
      align="center"
      prop="monthlyBaseSalary"
      label="月薪(萬)"
      width="120"
      sortable
    ></el-table-column>
    <el-table-column
      align="center"
      prop="monthlyBonus"
      label="Bonus(月)"
      width="120"
    ></el-table-column>
    <el-table-column
      align="center"
      prop="totalAnnualCompensation"
      label="總共年薪(萬)"
      width="140"
      sortable
    ></el-table-column>
    <el-table-column
      align="center"
      prop="dailyAverageWorkingHours"
      label="每日工時(H)"
      width="140"
      sortable
    ></el-table-column>
    <el-table-column
      align="center"
      prop="monthlyOvertime"
      label="每月加班(H)"
      width="140"
    ></el-table-column>
    <el-table-column
      align="center"
      prop="overtimeFrequency"
      label="加班頻率(1~5)"
      width="160"
      sortable
    ></el-table-column>
    <el-table-column
      align="center"
      prop="jobSatisfaction"
      label="爽度(1~5)"
      width="140"
      sortable
    ></el-table-column>
    <el-table-column
      align="center"
      prop="loading"
      label="工作量(1~5)"
      width="140"
      sortable
    ></el-table-column>
    <el-table-column
      align="center"
      prop="supplement"
      label="心得 || 建議 || 推薦 || 補充說明"
      width="360"
    ></el-table-column>
  </el-table>
</template>
