server:
  port: 8080

spring:
#  mvc:
#    servlet:
#      path: /tech_salary
  application:
    name: SinShui
  datasource:
#    initialization-mode: never
#    name: test
#    url: jdbc:mysql://127.0.0.1:3306/tech_salary
    url: jdbc:mysql://db:3306/tech_salary
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false

#  redis:
#    host: localhost
#    port: 6379
#    database: 0

  # swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger

logging:
  charset: UTF-8
#    disable-swagger-default-url: true


